### ISSUE TITLE
decoder/mod.rs has infinite recursion in `impl Display`

### ISSUE THREAD

**Issue by compenguy** [RustAudio/rodio#377]
When an error is thrown by decoder it causes infinite recursion:

```
#0  0x000055555599b674 in alloc::string::String::new ()                                                        [0/1306]
    at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/string.rs:379
#1  0x00005555559a9b70 in alloc::string::{{impl}}::to_string<rodio::decoder::DecoderError> (self=0x5555568edce0)
    at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/string.rs:2379
#2  0x00005555559ac3fd in rodio::decoder::{{impl}}::fmt (self=0x5555568edce0, f=0x7fffff7ff170)
    at /home/wpage/.cargo/git/checkouts/rodio-6458f6e95b054746/0988e8c/src/decoder/mod.rs:545
#3  0x00005555559a9b9f in alloc::string::{{impl}}::to_string<rodio::decoder::DecoderError> (self=0x5555568edce0)
    at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/string.rs:2382
#4  0x00005555559ac3fd in rodio::decoder::{{impl}}::fmt (self=0x5555568edce0, f=0x7fffff7ff2a0)
    at /home/wpage/.cargo/git/checkouts/rodio-6458f6e95b054746/0988e8c/src/decoder/mod.rs:545
#5  0x00005555559a9b9f in alloc::string::{{impl}}::to_string<rodio::decoder::DecoderError> (self=0x5555568edce0)
    at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/string.rs:2382
#6  0x00005555559ac3fd in rodio::decoder::{{impl}}::fmt (self=0x5555568edce0, f=0x7fffff7ff3d0)
    at /home/wpage/.cargo/git/checkouts/rodio-6458f6e95b054746/0988e8c/src/decoder/mod.rs:545
#7  0x00005555559a9b9f in alloc::string::{{impl}}::to_string<rodio::decoder::DecoderError> (self=0x5555568edce0)
    at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/string.rs:2382
#8  0x00005555559ac3fd in rodio::decoder::{{impl}}::fmt (self=0x5555568edce0, f=0x7fffff7ff500)
    at /home/wpage/.cargo/git/checkouts/rodio-6458f6e95b054746/0988e8c/src/decoder/mod.rs:545
#9  0x00005555559a9b9f in alloc::string::{{impl}}::to_string<rodio::decoder::DecoderError> (self=0x5555568edce0)
    at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/string.rs:2382
...
```

This is a result of implementing the `Display` trait on a type, and calling `self.to_string()` in its implementation.  The default implementation of `ToString` for sized types that implement `Display` relies on `Display` to implement `to_string()`, causing the the infinite recursion seen here.

Conventionally, this is resolved by writing the individual fields of the type to the formatter directly.

**Comment by est31** [comment]
edc60950b66991e57a38e9d00a1ebaa6d5fd6417
