### ISSUE TITLE
Panic when decoding mp3 file

### ISSUE THREAD

**Issue by a1phyr** [RustAudio/rodio#411]
I tried to read the following mp3 file: [silence.zip](https://github.com/RustAudio/rodio/files/7969043/silence.zip).

With `rodio` 0.14 it works as expected but `rodio` 0.15 panics when calling `Decoder::new_mp3`.

I used the following code to read it:

```rust
fn main() {
    let data = std::io::Cursor::new(include_bytes!("silence.mp3"));
    assert!(rodio::decoder::Decoder::new_mp3(data).is_ok());
}
```

**Comment by est31** [comment]
Can you share the backtrace? Is this with `minimp3` or `symphonia`?

**Comment by a1phyr** [comment]
The panic only happens with `minimp3`, not `symphonia`.

Sorry for forgetting the backtrace, here it is:

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Eof', /home/alphyr/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.15.0/src/decoder/mp3.rs:26:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: rodio::decoder::mp3::Mp3Decoder<R>::new
             at /home/alphyr/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.15.0/src/decoder/mp3.rs:26:29
   5: rodio::decoder::Decoder<R>::new_mp3
             at /home/alphyr/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.15.0/src/decoder/mod.rs:163:15
   6: rodio_bug::main
             at ./src/main.rs:3:13
   7: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by est31** [comment]
Interesting, that code wasn't touched in the update. Maybe a git bisection would help?

**Comment by est31** [comment]
@a1phyr can you add rodio as a git dependency and then do a manual git bisection as in, try out the middle commit between the two releases, then continue halving your search area?

**Comment by a1phyr** [comment]
Actually [this commit](https://github.com/RustAudio/rodio/commit/0988e8c886fbbe57b4b0771259c65dc26f83eb2c#diff-e4bd91e256a3eb5d5fc178cd8187db20444258c2b8002bbc0cda3ac2e0822d22R26) added the failing `unwrap.

A quick test shows that the panic didn't happen before

**Comment by est31** [comment]
Oh that's interesting. And before it's not returning an erorr but instead does playback just fine? Indeed, an unwrap is not good.

**Comment by Nisse43** [comment]
+1 on this.

**Comment by LighghtEeloo** [comment]
+1 on this.

**Comment by roderickvd** [comment]
I can confirm that this works for both `minimp3` and `symphonia-mp3` today, and will add a test case to prevent regression in #768.
